# Generated by Django 3.1.1 on 2022-03-12 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(default=1, unique=True, verbose_name='User id')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='ZontImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zont_id', models.BigIntegerField(blank=True, null=True, verbose_name='Zont id')),
                ('images', models.TextField(verbose_name='Images list')),
            ],
            options={
                'verbose_name': 'Zont image',
                'verbose_name_plural': 'Zonts Images',
            },
        ),
        migrations.CreateModel(
            name='Zonts',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zont_id', models.BigIntegerField(blank=True, null=True, verbose_name='Zont id')),
                ('location', models.URLField(verbose_name='Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Zont',
                'verbose_name_plural': 'Zonts',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.TextField(blank=True, null=True, verbose_name='All images')),
                ('question', models.TextField(verbose_name='Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255, verbose_name='Image')),
                ('where', models.CharField(max_length=255, verbose_name='Where illness')),
                ('type_illness', models.CharField(max_length=255, verbose_name='Type illness')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Problem',
                'verbose_name_plural': 'Problems',
            },
        ),
    ]
